### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cache/2019-05-03.txt'

### ISSUE THREAD

**Issue by 89171** [LewisTian/bili-box#1]
直接运行报这个错误，创建cache文件夹之后可以运行，但是下载完成的视频都变成空文件夹，找不到flv文件了

**Comment by taseikyo** [comment]
之前那个旧的 api 不能用了，然后找了新的 api 改了代码，但没重新打包程序，你可以下载代码运行

**Comment by 89171** [comment]
之前没有接触过python，执行了下面的命令打包
pip install pywin32
pip install PyInstaller
pyinstaller -F main.py
打包完成之后执行python  main.py不过还是一样。正在下载中有下载的flv文件，下载完成就变成空文件夹了

**Comment by taseikyo** [comment]
我这没问题啊，可以看这个图
![preview](https://user-images.githubusercontent.com/23132915/57187006-50171180-6f1b-11e9-9947-6b8396d8cf6a.gif)
flv 不见了是因为转成 mp4 了，至于变成空文件夹，我不知道欸
那个打包命令有问题，应该是 `pyinstaller -F -w main.py -p mwin.py -p res_rc.py -i bilibili.ico`
之后会生成一个 dist 文件夹，里面就是打包好的程序，将 cache，images，setting.ini 复制进去就可以运行了

**Comment by 89171** [comment]
找到了解决方法：
注释了main.py文件中change2mp4方法的最后一行os.remove(x)，取消flv文件删除

**Comment by roachsinai** [comment]
`No such file or directory: 'cache/2019-05-03.txt'` 这个报错是因为cache文件夹不存在，git提交的时候不包含空文件夹。
